version: 0.2

phases:
  install:
    commands:
      - pip3 install --upgrade awscli
      - npm install
      - TEST_ONE="echo $PUBLIC_PATH"
      - TEST_TWO="$PUBLIC_PATH"
      - npm run live
      - aws s3 sync --delete dist/ $APP_BUCKET/apps/portfolio-2021