version: 0.2

phases:
  install:
    commands:
      - pip3 install --upgrade awscli
      - npm install
      - npm install -D webpack-cli
      - aws s3 sync --delete dist/ $APP_BUCKET/apps/portfolio-2021 && yes