version: 0.2

phases:
  install:
    commands:
      - pip3 install --upgrade awscli
      - npm install
      - webpack --mode production --env.MODE=live << $"yes"
      - aws s3 sync --delete dist/ $APP_BUCKET/apps/portfolio-2021